[package]
authors = ["Johann Woelper <woelper@gmail.com>"]
description = "A minimalistic image viewer with analysis and editing tools"
edition = "2018"
exclude = [
  "res/*.gif",
]
keywords = ["graphics", "image", "viewer"]
license = "MIT"
name = "oculante"
readme = "README.md"
repository = "https://github.com/woelper/oculante/"
version = "0.6.57"

[package.metadata.bundle]
icon = ["res/oculante.png"]
identifier = "com.github.woelper.oculante"
name = "oculante"

[dependencies]
anyhow = "1.0"
arboard = "3.2"
avif-decode = {version = "0.2.2", optional = true}
clap = "3.2"
dds-rs = "0.7.0"
dirs = "5.0"
env_logger = "0.10"
evalexpr = "8.1"
exr = "1.5"
fast_image_resize = "2.4.0"
gif = "0.12"
gif-dispose = "4"
image = "0.24"
jpegxl-rs = {version = "0.8", optional = true, default-features = false, features = ["vendored", "image"]}
kamadak-exif = "0.5"
lexical-sort = "0.3.1"
libavif-image = {version = "0.10.0", optional = true}
libwebp-sys = "0.9"
log = "0.4"
nalgebra = "0.32"
notan = {version = "0.9", default-features = false, features = ["backend", "draw", "glsl-to-spirv","drop_files", "egui"]}
palette = "0.6"
psd = "0.3"
quickraw = "0.1.6"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.5"
resvg = "0.30"
rfd = {version = "0.11.0", optional = true}
rgb = "0.8"
self_update = {version = "0.36", default-features = false, features = ["rustls"], optional = true}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
strum = {version = "0.24", features = ["derive"]}
strum_macros = "0.24"
tiny-skia = "0.8.2"
tonemap = "0.0.4"
turbojpeg = {version = "0.5", features = ["image"], optional = true}
usvg = "0.30"
webbrowser = "0.8"
lazy_static = "*"

[features]
avif_native = ["avif-decode"]
dav1d = ["libavif-image"]
default = ["turbo", "file_open", "avif_native", "update"]
file_open = ["rfd"]
jpgxl = ["jpegxl-rs"]
turbo = ["turbojpeg"]
update = ["self_update"]

[target.'cfg(target_os = "macos")'.dependencies]
fruitbasket = "0.10.0"

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[build-dependencies]
env_logger = "0.10.0"
log = "0.4.14"
winres = "0.1"

[dev-dependencies]
cmd_lib = "1.3.0"

[profile.release]
# codegen-units = 1
# incremental = false
lto = "thin"
strip = true
# opt-level = "z"
panic = "abort"

[profile.dev]
debug = false
incremental = true
opt-level = 1

