[package]
authors = ["Johann Woelper <woelper@gmail.com>"]
description = "A minimalistic image viewer with analysis and editing tools"
edition = "2018"
keywords = ["graphics", "image", "viewer"]
license = "MIT"
name = "oculante"
readme = "README.md"
repository = "https://github.com/woelper/oculante/"
version = "0.6.23"

[package.metadata.bundle]
icon = ["res/oculante.png"]
identifier = "com.github.woelper.oculante"
name = "oculante"

[dependencies]
anyhow = "1.0"
arboard = "3.2"
clap = "3.2"
dds-rs = "0.7.0"
dirs = "4.0"
env_logger = "0.10"
evalexpr = "8.1"
exr = "1.5"
gif = "0.12"
gif-dispose = "4"
image = "0.24"
kamadak-exif = "0.5"
libwebp-sys = "0.8"
log = "0.4"
nalgebra = "0.31"
notan = {version = "0.8", features = ["drop_files", "egui"]}
palette = "0.6"
psd = "0.3"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.5"
resvg = "0.27.0"
rgb = "0.8.3"
self_update = "0.32"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
strum = {version = "0.24", features = ["derive"]}
strum_macros = "0.24"
tiny-skia = "0.8.2"
turbojpeg = {version = "0.5", features = ["image"], optional = true}
usvg = "0.27.0"
webbrowser = "0.8"

pdf = { git = "https://github.com/pdf-rs/pdf" }
pdf_render = { git = "https://github.com/pdf-rs/pdf_render.git"}
argh = "*"
pathfinder_rasterize = { git = "https://github.com/s3bk/pathfinder_rasterizer" }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder" }

[features]
default = ["turbo"]
turbo = ["turbojpeg"]

[target.'cfg(target_os = "macos")'.dependencies]
fruitbasket = "0.10.0"

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[build-dependencies]
env_logger = "0.10.0"
log = "0.4.14"
winres = "0.1"

[dev-dependencies]
cmd_lib = "1.3.0"

[profile.release]
codegen-units = 1
incremental = true
lto = "thin"
strip = true
# opt-level = "z"
panic = "abort"

[profile.dev]
debug = false
incremental = true
opt-level = 1
